spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  application:
    name: finance-control
  profiles:
    active: ${PROFILE:local}
  hateoas:
    use-hal-as-default-json-media-type: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  use-management-port: false
  default-media-type: application/json
  use-hal-as-default-media-type: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
